# Generated by Django 4.1.5 on 2023-01-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='here', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.CharField(default='here', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(default='here'),
            preserve_default=False,
        ),
    ]
