# Generated by Django 4.1.5 on 2023-01-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.FloatField(),
        ),
    ]
